//---------------------------------------------------------------------------

#ifndef GridViewH
#define GridViewH
//---------------------------------------------------------------------------
#include <System.Classes.hpp>
#include <FMX.Controls.hpp>
#include <FMX.Forms.hpp>
#include <FMX.Layouts.hpp>
#include <FMX.ListBox.hpp>
#include <FMX.Types.hpp>
#include <FMX.Ani.hpp>
#include <FMX.Gestures.hpp>
#include <Data.DB.hpp>
#include <Data.Win.ADODB.hpp>
#include <Data.Bind.Components.hpp>
#include <Data.Bind.DBScope.hpp>
#include <Data.Bind.EngExt.hpp>
#include <Fmx.Bind.DBEngExt.hpp>
#include <Fmx.Bind.Editors.hpp>
#include <Fmx.Bind.Navigator.hpp>
#include <FMX.Edit.hpp>
#include <System.Bindings.Outputs.hpp>
#include <System.Rtti.hpp>
#include <FMX.Menus.hpp>
#include <FMX.Objects.hpp>
#include <FMX.ExtCtrls.hpp>
#include <Data.Bind.Grid.hpp>
#include <Fmx.Bind.Grid.hpp>
#include <FMX.Grid.hpp>
#include <FMX.Colors.hpp>
#include <Data.FMTBcd.hpp>
#include <Data.SqlExpr.hpp>
//---------------------------------------------------------------------------
class TGridViewForm : public TForm
{
__published:	// IDE-managed Components
	TLayout *MainLayout;
	TLayout *HeaderLayout;
	TLabel *TitleLabel1;
	THorzScrollBox *HorzScrollBox1;
	TLayout *GroupLayout1;
	TListBox *ListBox1;
	TMetropolisUIListBoxItem *MetroListBoxItem6;
	TMetropolisUIListBoxItem *MetroListBoxItem1;
	TMetropolisUIListBoxItem *MetroListBoxItem2;
	TLayout *ToolbarHolder;
	TPopup *ToolbarPopup;
	TToolBar *ToolBar1;
	TButton *ToolbarApplyButton;
	TButton *ToolbarCloseButton;
	TButton *ToolbarAddButton;
	TFloatAnimation *ToolbarPopupAnimation;
	TBindSourceDB *BindSourceDB1;
	TBindingsList *BindingsList1;
	TMainMenu *MainMenu1;
	TMenuItem *MenuItem1;
	TMenuItem *MenuItem2;
	TMenuItem *MenuItem3;
	TMenuItem *MenuItem4;
	TMenuItem *MenuItem5;
	TMenuItem *MenuItem6;
	TMenuItem *MenuItem7;
	TMetropolisUIListBoxItem *MetroListBoxItem7;
	TMetropolisUIListBoxItem *MetropolisUIListBoxItem1;
	TMetropolisUIListBoxItem *MetropolisUIListBoxItem2;
	TMetropolisUIListBoxItem *MetropolisUIListBoxItem3;
	TMetropolisUIListBoxItem *MetropolisUIListBoxItem4;
	TMenuItem *MenuItem8;
	TMenuItem *MenuItem9;
	TMenuItem *MenuItem10;
	TMenuItem *MenuItem11;
	TMenuItem *MenuItem12;
	TMenuItem *MenuItem13;
	TMenuItem *MenuItem14;
	TLabel *Label1;
	TADOConnection *ADOConnection1;
	TADOQuery *ADOQuery1;
	TLabel *Label2;
	TMenuItem *MenuItem15;
	TMenuItem *MenuItem16;
	TMenuItem *MenuItem17;
	TMenuItem *MenuItem18;
	TMenuItem *MenuItem19;
	TMenuItem *MenuItem20;
	TMenuItem *MenuItem21;
	TMenuItem *MenuItem24;
	TMetropolisUIListBoxItem *MetropolisUIListBoxItem5;
	TMetropolisUIListBoxItem *MetropolisUIListBoxItem6;
	TMenuItem *MenuItem22;
	TMenuItem *MenuItem23;
	TMenuItem *MenuItem25;
	TMenuItem *MenuItem26;
	TMenuItem *MenuItem27;
	TMenuItem *MenuItem28;
	TMenuItem *MenuItem29;
	TMenuItem *MenuItem30;
	TMenuItem *MenuItem31;
	TMenuItem *MenuItem33;
	TImage *Image1;
	TMenuItem *MenuItem34;
	TMenuItem *MenuItem32;
	TMenuItem *MenuItem35;
	TMenuItem *MenuItem36;
	TMenuItem *MenuItem37;
	TMenuItem *MenuItem38;
	TMenuItem *MenuItem39;
	TPopupMenu *PopupMenu2;
	TMenuItem *MenuItem40;
	TMenuItem *MenuItem41;
	TMenuItem *MenuItem42;
	TMenuItem *MenuItem43;
	TMenuItem *MenuItem44;
	TMenuItem *MenuItem46;
	TMenuItem *MenuItem47;
	TMenuItem *MenuItem48;
	TMenuItem *MenuItem49;
	TMenuItem *MenuItem50;
	TMenuItem *MenuItem51;
	TMenuItem *MenuItem52;
	TMenuItem *MenuItem53;
	TMenuItem *MenuItem54;
	TMenuItem *MenuItem55;
	TMenuItem *MenuItem56;
	TMenuItem *MenuItem57;
	TMenuItem *MenuItem58;
	TMenuItem *MenuItem59;
	TMenuItem *MenuItem60;
	TMenuItem *MenuItem62;
	TMenuItem *MenuItem63;
	TMenuItem *MenuItem64;
	TMenuItem *MenuItem65;
	TMenuItem *MenuItem66;
	TMenuItem *MenuItem67;
	TMenuItem *MenuItem68;
	TMenuItem *MenuItem69;
	TMenuItem *MenuItem70;
	TMenuItem *MenuItem72;
	TMenuItem *MenuItem73;
	TMenuItem *MenuItem74;
	TMenuItem *MenuItem75;
	TMenuItem *MenuItem76;
	TMenuItem *MenuItem77;
	TMenuItem *MenuItem78;
	TMenuItem *MenuItem80;
	TMenuItem *MenuItem81;
	TMenuItem *MenuItem82;
	TMenuItem *MenuItem83;
	TMenuItem *MenuItem86;
	TMenuItem *MenuItem87;
	TMenuItem *MenuItem88;
	TMenuItem *MenuItem89;
	TMenuItem *MenuItem90;
	TMenuItem *MenuItem91;
	TMenuItem *MenuItem92;
	TMenuItem *MenuItem93;
	TMenuItem *MenuItem96;
	TMenuItem *MenuItem97;
	TMenuItem *MenuItem98;
	TMenuItem *MenuItem99;
	TMenuItem *MenuItem100;
	TMenuItem *MenuItem101;
	TMenuItem *MenuItem102;
	TMenuItem *MenuItem103;
	TMenuItem *MenuItem104;
	TMenuItem *MenuItem106;
	TMenuItem *MenuItem107;
	TMenuItem *MenuItem108;
	TMenuItem *MenuItem109;
	TMenuItem *MenuItem110;
	TMenuItem *MenuItem111;
	TMenuItem *MenuItem112;
	TMenuItem *MenuItem114;
	TMenuItem *MenuItem115;
	TMenuItem *MenuItem116;
	TMenuItem *MenuItem117;
	TMenuItem *MenuItem118;
	TMenuItem *MenuItem119;
	TMenuItem *MenuItem121;
	TMenuItem *MenuItem122;
	TToolBar *ToolBar2;
	TCornerButton *CornerButton1;
	TCornerButton *CornerButton2;
	TCornerButton *CornerButton3;
	TCornerButton *CornerButton4;
	TCornerButton *CornerButton6;
	TMenuItem *MenuItem123;
	TMenuItem *MenuItem124;
	TMenuItem *MenuItem125;
	TMenuItem *MenuItem126;
	TMenuItem *MenuItem128;
	TMenuItem *MenuItem129;
	TMenuItem *MenuItem130;
	TMenuItem *MenuItem131;
	TMenuItem *MenuItem71;
	TMenuItem *MenuItem94;
	TMenuItem *MenuItem95;
	TADOQuery *ADOQuery2;
	TProgressBar *ProgressBarOverDue;
	TLabel *Label3;
	TLabel *Label4;
	TLabel *Label5;
	TLabel *Label6;
	TLabel *Label7;
	TLabel *Label8;
	TLabel *Label9;
	TLabel *Label10;
	TLabel *Label11;
	TProgressBar *ProgressBarZero;
	TProgressBar *ProgressBarTicketInprocess;
	TProgressBar *ProgressBarItemsInprocess;
	TProgressBar *ProgressBarTicketsOverdue;
	TProgressBar *ProgressBarItemsOverdue;
	TProgressBar *ProgressBarReady;
	TProgressBar *ProgressBarQuick;
	TProgressBar *ProgressBarTransactions;
	TSpeedButton *SpeedButton1;
	TLabel *Label12;
	TLabel *Label13;
	TLabel *Label14;
	TLabel *Label15;
	TLabel *Label16;
	TLabel *Label17;
	TLabel *Label18;
	TLabel *Label19;
	TLabel *Label20;
	TLabel *Label21;
	TProgressBar *ProgressBar1;
	TMenuItem *MenuItem105;
	TMenuItem *MenuItem120;
	TMenuItem *MenuItem133;
	TMenuItem *MenuItem134;
	TGrid *Grid1;
	TADOQuery *ADOQuery3;
	TBindSourceDB *BindSourceDB2;
	TLinkGridToDataSource *LinkGridToDataSource1;
	TButton *Button1;
	TButton *Button2;
	TButton *Button3;
	TButton *Button4;
	TButton *Button5;
	TButton *Button6;
	TButton *Button7;
	TButton *Button8;
	TButton *Button9;
	TMenuItem *MenuItem136;
	TMenuItem *MenuItem137;
	TButton *Button10;
	TMenuItem *MenuItem138;
	TMenuItem *MenuItem139;
	TMenuItem *MenuItem140;
	TMenuItem *MenuItem141;
	TImage *Image2;
	TMenuItem *MenuItem142;
	TMenuItem *MenuItem143;
	TImage *Image3;
	TImage *Image4;
	TImage *Image5;
	TImage *Image6;
	TMenuItem *MenuItem144;
	TMenuItem *MenuItem145;
	TMenuItem *MenuItem146;
	TColorComboBox *ColorComboBox1;
	TLabel *Label22;
	TADOQuery *ADOQuery4;
	TCalendarEdit *CalendarEdit1;
	TLabel *Label23;
	TMetropolisUIListBoxItem *MetropolisUIListBoxItem7;
	TMetropolisUIListBoxItem *MetropolisUIListBoxItem8;
	TMenuItem *MenuItem147;
	TMenuItem *MenuItem148;
	TMenuItem *MenuItem79;
	TMenuItem *MenuItem149;
	TMetropolisUIListBoxItem *MetropolisUIListBoxItem9;
	TMetropolisUIListBoxItem *MetropolisUIListBoxItem10;
	TMetropolisUIListBoxItem *MetropolisUIListBoxItem11;
	TMetropolisUIListBoxItem *MetropolisUIListBoxItem12;
	TMetropolisUIListBoxItem *MetropolisUIListBoxItem13;
	TMetropolisUIListBoxItem *MetropolisUIListBoxItem14;
	TADOCommand *ADOCommand1;
	TMenuItem *MenuItem113;
	TMenuItem *MenuItem127;
	TADOConnection *ADOConnection2;
	TMenuItem *MenuItem61;
	TMenuItem *MenuItem45;
	TMenuItem *MenuItem84;
	TMenuItem *MenuItem85;
	TMenuItem *MenuItem132;
	TMenuItem *MenuItem135;
	TMenuItem *MenuItem150;
	TMenuItem *MenuItem151;
	TImage *Image7;
	TMenuItem *MenuItem152;
	TMenuItem *MenuItem153;
	TMenuItem *MenuItem154;
	TADOQuery *ADOQuery5;
	TMenuItem *MenuItem155;
	TMenuItem *MenuItem156;
	TADOQuery *ADOQuery6;
	TADOQuery *ADOQuery7;
	TSqlServerMethod *SqlServerMethod1;

	void __fastcall ItemClick(TObject *Sender);
	void __fastcall FormGesture(TObject *Sender, const TGestureEventInfo &EventInfo,
          bool &Handled);
	void __fastcall FormMouseUp(TObject *Sender, TMouseButton Button, TShiftState Shift,
		  float X, float Y);
	void __fastcall ToolbarCloseButtonClick(TObject *Sender);
	void __fastcall FormKeyDown(TObject *Sender, WORD &Key, System::WideChar &KeyChar,
          TShiftState Shift);
	void __fastcall MetroListBoxItem7Click(TObject *Sender);
	void __fastcall MenuItem8Click(TObject *Sender);
	void __fastcall MetroListBoxItem2Click(TObject *Sender);
	void __fastcall MetroListBoxItem6Click(TObject *Sender);
	void __fastcall MetroListBoxItem1Click(TObject *Sender);
	void __fastcall FormShow(TObject *Sender);
	void __fastcall MenuItem16Click(TObject *Sender);
	void __fastcall MenuItem17Click(TObject *Sender);
	void __fastcall MenuItem7Click(TObject *Sender);
	void __fastcall MenuItem6Click(TObject *Sender);
	void __fastcall MenuItem18Click(TObject *Sender);
	void __fastcall MenuItem19Click(TObject *Sender);
	void __fastcall MenuItem21Click(TObject *Sender);
	void __fastcall MenuItem20Click(TObject *Sender);
	void __fastcall MetropolisUIListBoxItem4Click(TObject *Sender);
	void __fastcall MetropolisUIListBoxItem2Click(TObject *Sender);
	void __fastcall MetropolisUIListBoxItem1Click(TObject *Sender);
	void __fastcall MenuItem13Click(TObject *Sender);
	void __fastcall MenuItem14Click(TObject *Sender);
	void __fastcall MetropolisUIListBoxItem6Click(TObject *Sender);
	void __fastcall MetropolisUIListBoxItem5Click(TObject *Sender);
	void __fastcall MetropolisUIListBoxItem3Click(TObject *Sender);
	void __fastcall MenuItem23Click(TObject *Sender);
	void __fastcall MenuItem25Click(TObject *Sender);
	void __fastcall MenuItem26Click(TObject *Sender);
	void __fastcall MenuItem31Click(TObject *Sender);
	void __fastcall MenuItem32Click(TObject *Sender);
	void __fastcall MenuItem33Click(TObject *Sender);
	void __fastcall Image1Click(TObject *Sender);
	void __fastcall MenuItem9Click(TObject *Sender);
	void __fastcall MenuItem10Click(TObject *Sender);
	void __fastcall MenuItem11Click(TObject *Sender);
	void __fastcall MenuItem34Click(TObject *Sender);
	void __fastcall MenuItem35Click(TObject *Sender);
	void __fastcall MenuItem37Click(TObject *Sender);
	void __fastcall MenuItem38Click(TObject *Sender);
	void __fastcall MenuItem39Click(TObject *Sender);
	void __fastcall MenuItem40Click(TObject *Sender);
	void __fastcall MenuItem41Click(TObject *Sender);
	void __fastcall MenuItem42Click(TObject *Sender);
	void __fastcall MenuItem43Click(TObject *Sender);
	void __fastcall MenuItem44Click(TObject *Sender);
	void __fastcall MenuItem45Click(TObject *Sender);
	void __fastcall MenuItem46Click(TObject *Sender);
	void __fastcall MenuItem108Click(TObject *Sender);
	void __fastcall MenuItem122Click(TObject *Sender);
	void __fastcall CornerButton1Click(TObject *Sender);
	void __fastcall CornerButton2Click(TObject *Sender);
	void __fastcall CornerButton3Click(TObject *Sender);
	void __fastcall MenuItem65Click(TObject *Sender);
	void __fastcall MenuItem66Click(TObject *Sender);
	void __fastcall MenuItem48Click(TObject *Sender);
	void __fastcall MenuItem47Click(TObject *Sender);
	void __fastcall MenuItem50Click(TObject *Sender);
	void __fastcall MenuItem51Click(TObject *Sender);
	void __fastcall MenuItem53Click(TObject *Sender);
	void __fastcall MenuItem64Click(TObject *Sender);
	void __fastcall MenuItem62Click(TObject *Sender);
	void __fastcall MenuItem63Click(TObject *Sender);
	void __fastcall MenuItem67Click(TObject *Sender);
	void __fastcall MenuItem68Click(TObject *Sender);
	void __fastcall MenuItem70Click(TObject *Sender);
	void __fastcall CornerButton4Click(TObject *Sender);
	void __fastcall MenuItem71Click(TObject *Sender);
	void __fastcall MenuItem102Click(TObject *Sender);
	void __fastcall MenuItem103Click(TObject *Sender);
	void __fastcall MenuItem104Click(TObject *Sender);
	void __fastcall MenuItem72Click(TObject *Sender);
	void __fastcall MenuItem73Click(TObject *Sender);
	void __fastcall MenuItem74Click(TObject *Sender);
	void __fastcall MenuItem75Click(TObject *Sender);
	void __fastcall MenuItem76Click(TObject *Sender);
	void __fastcall MenuItem77Click(TObject *Sender);
	void __fastcall MenuItem78Click(TObject *Sender);
	void __fastcall MenuItem79Click(TObject *Sender);
	void __fastcall MenuItem80Click(TObject *Sender);
	void __fastcall MenuItem81Click(TObject *Sender);
	void __fastcall MenuItem82Click(TObject *Sender);
	void __fastcall MenuItem83Click(TObject *Sender);
	void __fastcall MenuItem84Click(TObject *Sender);
	void __fastcall MenuItem85Click(TObject *Sender);
	void __fastcall MenuItem69Click(TObject *Sender);
	void __fastcall MenuItem86Click(TObject *Sender);
	void __fastcall MenuItem87Click(TObject *Sender);
	void __fastcall MenuItem88Click(TObject *Sender);
	void __fastcall MenuItem89Click(TObject *Sender);
	void __fastcall MenuItem91Click(TObject *Sender);
	void __fastcall MenuItem92Click(TObject *Sender);
	void __fastcall MenuItem93Click(TObject *Sender);
	void __fastcall MenuItem94Click(TObject *Sender);
	void __fastcall MenuItem95Click(TObject *Sender);
	void __fastcall MenuItem96Click(TObject *Sender);
	void __fastcall MenuItem97Click(TObject *Sender);
	void __fastcall MenuItem98Click(TObject *Sender);
	void __fastcall MenuItem99Click(TObject *Sender);
	void __fastcall MenuItem100Click(TObject *Sender);
	void __fastcall MenuItem61Click(TObject *Sender);
	void __fastcall CornerButton5Click(TObject *Sender);
	void __fastcall UpdateMenu();
	void __fastcall CornerButton6Click(TObject *Sender);
	void __fastcall MenuItem52Click(TObject *Sender);
	void __fastcall MenuItem123Click(TObject *Sender);
	void __fastcall MenuItem124Click(TObject *Sender);
	void __fastcall MenuItem127Click(TObject *Sender);
	void __fastcall MenuItem126Click(TObject *Sender);
	void __fastcall MenuItem128Click(TObject *Sender);
	void __fastcall MenuItem129Click(TObject *Sender);
	void __fastcall MenuItem120Click(TObject *Sender);
	void __fastcall MenuItem130Click(TObject *Sender);
	void __fastcall MenuItem117Click(TObject *Sender);
	void __fastcall CornerButton7Click(TObject *Sender);
	void __fastcall MenuItem125Click(TObject *Sender);
	void __fastcall MenuItem131Click(TObject *Sender);
	void __fastcall MenuItem109Click(TObject *Sender);
	void __fastcall SpeedButton1Click(TObject *Sender);
	void __fastcall Button1Click(TObject *Sender);
	void __fastcall Button2Click(TObject *Sender);
	void __fastcall Button3Click(TObject *Sender);
	void __fastcall Button4Click(TObject *Sender);
	void __fastcall Button5Click(TObject *Sender);
	void __fastcall Button6Click(TObject *Sender);
	void __fastcall Button7Click(TObject *Sender);
	void __fastcall Button8Click(TObject *Sender);
	void __fastcall Button9Click(TObject *Sender);
	void __fastcall MenuItem116Click(TObject *Sender);
	void __fastcall MenuItem136Click(TObject *Sender);
	void __fastcall MenuItem137Click(TObject *Sender);
	void __fastcall Button10Click(TObject *Sender);
	void __fastcall MenuItem138Click(TObject *Sender);
	void __fastcall MenuItem139Click(TObject *Sender);
	void __fastcall MenuItem140Click(TObject *Sender);
	void __fastcall MenuItem141Click(TObject *Sender);
	void __fastcall Image2Click(TObject *Sender);
	void __fastcall MenuItem142Click(TObject *Sender);
	void __fastcall MenuItem143Click(TObject *Sender);
	void __fastcall Image5Click(TObject *Sender);
	void __fastcall Image3Click(TObject *Sender);
	void __fastcall Image6Click(TObject *Sender);
	void __fastcall MenuItem144Click(TObject *Sender);
	void __fastcall MenuItem145Click(TObject *Sender);
	void __fastcall MenuItem146Click(TObject *Sender);
	void __fastcall ColorComboBox1Change(TObject *Sender);
	void __fastcall MetropolisUIListBoxItem8Click(TObject *Sender);
	void __fastcall MetropolisUIListBoxItem7Click(TObject *Sender);
	void __fastcall MetropolisUIListBoxItem9Click(TObject *Sender);
	void __fastcall MetropolisUIListBoxItem10Click(TObject *Sender);
	void __fastcall MetropolisUIListBoxItem11Click(TObject *Sender);
	void __fastcall MetropolisUIListBoxItem14Click(TObject *Sender);
	void __fastcall MetropolisUIListBoxItem12Click(TObject *Sender);
	void __fastcall MetropolisUIListBoxItem13Click(TObject *Sender);
	void __fastcall MenuItem106Click(TObject *Sender);
	void __fastcall MenuItem105Click(TObject *Sender);
	void __fastcall MenuItem107Click(TObject *Sender);
	void __fastcall MenuItem134Click(TObject *Sender);
	void __fastcall MenuItem147Click(TObject *Sender);
	void __fastcall MenuItem113Click(TObject *Sender);
	void __fastcall MenuItem115Click(TObject *Sender);
	void __fastcall Image4Click(TObject *Sender);
	void __fastcall MenuItem132Click(TObject *Sender);
	void __fastcall MenuItem135Click(TObject *Sender);
	void __fastcall MenuItem150Click(TObject *Sender);
	void __fastcall MenuItem151Click(TObject *Sender);
	void __fastcall GroupLayout1Click(TObject *Sender);
	void __fastcall Image7Click(TObject *Sender);
	void __fastcall MenuItem152Click(TObject *Sender);
	void __fastcall CalendarEdit1Change(TObject *Sender);
	void __fastcall MenuItem153Click(TObject *Sender);
	void __fastcall MenuItem154Click(TObject *Sender);
	void __fastcall MenuItem155Click(TObject *Sender);
	void __fastcall MenuItem156Click(TObject *Sender);

private:	// User declarations
	TPointF FGestureOrigin;
	bool FGestureInProgress;

	void ShowToolbar(bool AShow);
public:		// User declarations
	__fastcall TGridViewForm(TComponent* Owner);
	AnsiString __fastcall ConvertDate(AnsiString argDateString);
	AnsiString strStoreNo;
	AnsiString strReportName;
	AnsiString strReportFileName;
	AnsiString strStoreName;
	AnsiString strStoreAddress;
	AnsiString strStoreCity;
	AnsiString strStoreState;
	AnsiString strStoreZip;
	AnsiString strStorePhone;
	AnsiString strUserName;
	AnsiString strUserID;
	AnsiString strUserEmail;
	AnsiString strCityState;
	AnsiString strPaidType;
	AnsiString strReportFilter;
	AnsiString strStockNumber;
	AnsiString strVersionNumber;
	AnsiString strPickupAccount;
	AnsiString strPickupZip;
	AnsiString strPickupAddress;
	AnsiString strDescription;
	AnsiString strDataSet;
	AnsiString strCustomerAcct;
	AnsiString strDefaultEditTicketNumber;
	AnsiString strTicketNumber;
	AnsiString strQuestion;
    AnsiString strEnterQuantity;
	AnsiString strSenderEmail;
	AnsiString strSenderPassword;
	AnsiString strSendercc;
	AnsiString strSMTPServer;
	AnsiString strEmailSecurity;
	bool blnSendTicketEmail;
	bool blnIsQuickTicket;
	bool blnSendReadyEmail;
	AnsiString strEmailPort;
	bool blnOK;
	bool blnAdditionalTagInfo;
	bool blnRecalcTaxAfterCoupon;
	AnsiString strQuantityType;
	bool blnUseTags;
	AnsiString strNoTagsFor;
	AnsiString strSlave;
	double dDescriptionPrice;
	bool blnTicketClosed;
	bool blnUseMinFee;
	double fTendered;
	double iCouponPercent;
	double dCouponAmount;
	double fTaxRate;
	double fDeposit;
	bool blnPrePayAllToday;
	AnsiString strPrePayAccount;
	bool blnRepeat;
	bool blnWiderTags;
	bool blnPreview;
	bool blnAccountCustomer;
	AnsiString strDateOut;
	bool blnEnableTopMenu;
	double fPrepayment;
	bool blnDirectPrint;
	double fCouponTotal;
	double blnDirectPayment;
	double fTicketTax;
	bool blnDateOut;
	bool blnDateIn;
	AnsiString strDefaultStatus;
	AnsiString strCCard;
	AnsiString strExpDate;
    bool blnDefaultNewTaxable;
	bool blnAllowEditAccess;
		bool blnAllowCustomerAccess;
			bool blnAllowWriteAccess;
				bool blnAllowPickupAccess;
					bool blnAllowXChargeAccess;
						bool blnAllowTimeCardAccess;
							bool blnAllowInventoryAccess;
								bool blnAllowAccountAccess;
									bool blnAllowCashDrawerAccess;
										bool blnAllowPriceListAccess;
											bool blnAllowAssignLocationAccess;
												bool blnAllowMarkReadyAccess;


													bool blnAllowDeliveryAccess;
														bool blnAllowStoreAccess;
															bool blnAllowHotelAccess;
																bool blnAllowRouteAccess;




	bool blnTransactionLogin;
	bool blnWinExec;
	bool blnTagName;
	double fTicketSubTotal;
	double fLoyaltyDollars;
	bool blnAutoPopUpcharges;
	AnsiString strTicketPieceCount;
	AnsiString strTicketCopies;
	AnsiString strLastTicketNo;
	bool blnAutoPopupColor;
	AnsiString strTag1;
	AnsiString strTag2;
	AnsiString strTag3;
	bool blnDeposit;
	AnsiString strTag4;
	AnsiString strPC;
	AnsiString strTag5;
	AnsiString strTag6;
	AnsiString strTag7;
	bool blnSmallerItems;
	bool blnSeperateShirtLot;
	bool blnUseEuropeanFormat;
	bool blnUseInventoryControl;
	bool blnLocalDatabase;
	bool blnCancel;
	bool blnAutoStarch;
	bool blnDefaultLoyalty;
	bool blnUsePriceLevel;
	bool blnPayInFull;
	bool blnReturnTendered;
	bool blnBackButton;
	bool bln64Bit;
	bool blnUseCashDrawer;
	bool blnShowColorList;
	bool blnEnableEnterprise;
	bool blnDeliveryByDate;
	AnsiString strTicketPrinter;
	AnsiString strTagPrinter;
	bool blnEpsonU220Tag;
	bool blnDontPrintTags;
	bool blnNoTags;
	bool blnLargerDTags;
	bool blnTaxAllClasses;
	bool blnUseDeliveryVacation;
    double dTotalTicketValue;
	AnsiString strEnterprise;
	AnsiString strCustomerDiscount;
	AnsiString strLastSearch;
	bool blnLevelLoyalty;
	bool blnAutoSelectLastCustomer;
	bool blnUseCreditCardProcessing;
	AnsiString strCustomTicket;
	AnsiString strStarch;
	AnsiString strAdditionalFilter;
	AnsiString strCreditCardPath;
	AnsiString strSelectedClass;
	AnsiString strAccessLevel;
	AnsiString strPickupDate;
	AnsiString strStarchPreference;
	int intDaysToPickup;
	bool blnDisableDates;
	double dGiftCard;
	bool blnPrintTwice;
	AnsiString strPrintPause;
	bool blnPrint;
	AnsiString strCCReceiptPathPrinter;
	bool blnEmailOnly;
	AnsiString strSurchargeLabel;
	int iBackgroundColor;
	bool blnCustomerTaxable;
	bool blnShowReadyOnly;
	bool blnUseLotSystem;
	int intRackTicketNumber;
	bool blnUseRackTicket;
	int intCurrentLot;
	int intMaxItems;
	AnsiString strTicketComment;
	AnsiString strCustomerARStatement;
	AnsiString strEnvironmentalClasses;
	double dblEnvironmental;
	double dblActualEnvironmentalFee;
	double dblTotalEnvironmental;

};
//---------------------------------------------------------------------------
extern PACKAGE TGridViewForm *GridViewForm;
//---------------------------------------------------------------------------
#endif
